shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - ps: 'npm run test:dot #PowerShell'
  - cmd: npm run test:dot

cache:
  - node_modules
